# Chapter 3
## It starts with a tensor!

In [1]:
import torch
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [2]:
a[1]

tensor(1.)

In [3]:
float(a[1])

1.0

In [4]:
a[2] = 2.
a

tensor([1., 1., 2.])

In [5]:
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [6]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [7]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [8]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [9]:
points.shape

torch.Size([3, 2])

In [10]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [11]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [12]:
points[0, 1]

tensor(1.)

In [13]:
points[0]

tensor([4., 1.])

In [14]:
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [15]:
points[1:, :]

tensor([[5., 3.],
        [2., 1.]])

In [16]:
points[1:, 0]

tensor([5., 2.])

In [17]:
img_t = torch.randn(3, 5, 5)
img_t

tensor([[[-1.0891e+00,  1.0998e-01, -1.6473e-01,  1.6915e-01,  1.6928e+00],
         [ 2.0190e-01,  1.0554e+00,  9.2402e-01,  5.4782e-01, -2.3978e-01],
         [ 3.4687e-01,  2.7154e+00, -1.6360e+00, -1.7215e+00,  1.2798e+00],
         [ 2.2138e+00, -8.1591e-01, -9.4237e-01, -1.8560e-01,  1.5802e+00],
         [-8.5163e-01,  5.5462e-02,  9.1147e-01,  1.1983e+00, -4.3291e-01]],

        [[ 9.4425e-01,  1.7668e-01,  4.1391e-01, -3.2979e-01, -3.8178e-01],
         [ 2.4035e-01, -3.6148e-01, -9.0953e-01, -1.6758e+00,  1.8637e-01],
         [ 6.0550e-01, -5.3467e-01,  2.9378e-01, -1.2064e+00, -6.8194e-01],
         [ 2.6642e-01,  1.3116e+00, -7.8602e-01, -1.0812e+00,  1.0458e+00],
         [-5.9584e-01,  7.0755e-01, -1.3706e+00,  1.1197e+00,  5.4598e-01]],

        [[-2.6963e-01, -2.0932e-01, -6.3555e-01, -1.3598e-01, -1.5521e+00],
         [-1.2236e+00, -1.4023e+00, -3.9979e-01, -8.1134e-01,  2.0407e+00],
         [ 4.3554e-02,  2.0258e-01,  9.9905e-01,  9.8814e-02,  2.2964e+00],
        

In [32]:
weights = torch.tensor([0.2126, 0.7152, 0.0722])
weights

tensor([0.2126, 0.7152, 0.0722])

In [20]:
batch_t = torch.randn(2, 3, 5, 5)
batch_t

tensor([[[[ 0.4388, -0.8897, -0.8319, -0.2056, -0.0808],
          [ 0.4460, -0.1692, -0.6089, -0.5145,  0.2354],
          [-0.4781, -0.4112,  1.0263,  1.1938, -0.0287],
          [-0.2490,  0.5831,  0.5137,  0.3645, -0.8698],
          [-1.2519, -0.8371,  0.9993,  0.6977,  0.4451]],

         [[ 1.2600,  0.2066,  0.3616, -1.9593, -2.6945],
          [ 0.1349, -1.1773, -0.2606,  1.4781,  0.0767],
          [ 0.8998,  0.3224,  0.1400,  1.4978, -0.0186],
          [ 1.2660, -0.4113,  0.5201,  1.7532, -1.1175],
          [-1.2847, -0.0649, -1.1305,  0.7018, -0.9412]],

         [[ 0.2382,  0.3988, -0.4904, -0.4685,  1.4866],
          [-0.4698,  2.1554, -2.1341, -1.0899, -0.9437],
          [-0.4153,  1.0197,  1.1454,  0.1676,  1.1651],
          [-0.6052, -0.7761,  0.4153, -2.2237,  0.0571],
          [-1.3267,  1.6835, -0.1467, -1.2505, -0.5998]]],


        [[[-0.7372, -0.4552, -1.2940,  1.3815,  0.7857],
          [-0.4220, -1.4880,  0.6428, -2.6303, -0.1236],
          [ 0.2118,  0.

In [21]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [33]:
weights

tensor([0.2126, 0.7152, 0.0722])

In [34]:
weights.unsqueeze(-1)

tensor([[0.2126],
        [0.7152],
        [0.0722]])

In [27]:
# weights.unsqueeze_(-1)

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]])

In [38]:
weights.unsqueeze(-1).unsqueeze_(-1).shape

torch.Size([3, 1, 1])

In [39]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [40]:
img_gray_weighted_fancy = torch.einsum('...chw,c->...hw', img_t, weights)
batch_gray_weighted_fancy = torch.einsum('...chw,c->...hw', batch_t, weights)
batch_gray_weighted_fancy.shape

torch.Size([2, 5, 5])

In [41]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
weights_named

/tmp/ipykernel_24108/2371314847.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at ../c10/core/TensorImpl.h:1900.)
  weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [42]:
img_named = img_t.refine_names(..., 'channels', 'rows', 'columns')
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns')
print("img named:", img_named.shape, img_named.names)
print("batch named:", batch_named.shape, batch_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [43]:
weights_aligned = weights_named.align_as(img_named)
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [46]:
gray_named = (img_named * weights_aligned).sum('channels')
gray_named, gray_named.shape, gray_named.names

(tensor([[ 0.4243,  0.1346,  0.2151, -0.2097, -0.0252],
         [ 0.1265, -0.1354, -0.4829, -1.1406,  0.2297],
         [ 0.5099,  0.2095, -0.0656, -1.2217, -0.0498],
         [ 0.6956,  0.8684, -0.7400, -0.7900,  1.0467],
         [-0.5864,  0.4743, -0.6542,  1.0557,  0.2640]],
        names=('rows', 'columns')),
 torch.Size([5, 5]),
 ('rows', 'columns'))

In [47]:
gray_plain = gray_named.rename(None)
gray_plain, gray_plain.shape, gray_plain.names

(tensor([[ 0.4243,  0.1346,  0.2151, -0.2097, -0.0252],
         [ 0.1265, -0.1354, -0.4829, -1.1406,  0.2297],
         [ 0.5099,  0.2095, -0.0656, -1.2217, -0.0498],
         [ 0.6956,  0.8684, -0.7400, -0.7900,  1.0467],
         [-0.5864,  0.4743, -0.6542,  1.0557,  0.2640]]),
 torch.Size([5, 5]),
 (None, None))

### dtypes

In [52]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)
short_points.dtype, double_points.dtype

(torch.int16, torch.float64)

In [53]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()
short_points.dtype, double_points.dtype

(torch.int16, torch.float64)

In [54]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)
short_points.dtype, double_points.dtype

(torch.int16, torch.float64)

In [55]:
# When mixing input types in operations, the inputs are converted to the larger type automatically.
points_64 = torch.rand(5, dtype=torch.double)
points_short = points_64.to(torch.short)
points_64 * points_short

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [58]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1) # or a_t = a.transpose(0, 1)
a, a_t, a.shape, a_t.shape

(tensor([[1., 1.],
         [1., 1.],
         [1., 1.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 torch.Size([3, 2]),
 torch.Size([2, 3]))

In [59]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

/tmp/ipykernel_24108/2923139482.py:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [60]:
points_storage = points.storage()
points_storage[0], points_storage[4]

(4.0, 2.0)

In [61]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points # first element is changed from 4 to 2

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [62]:
# methods that have _ at the end of them are inplace like squeeze_ and zero_
a = torch.ones(3, 2)
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [63]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset()

2

In [64]:
second_point.size()

torch.Size([2])

In [65]:
second_point.shape

torch.Size([2])

In [66]:
points.stride()

(2, 1)

In [67]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points # 5 changed to 10

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [68]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points # 5 is not changed to 10

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [69]:
# transpose:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [70]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [71]:
id(points.storage()) == id(points_t.storage())

True

In [72]:
points.stride(), points_t.stride()

((2, 1), (1, 2))

In [73]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape, transpose_t.shape

(torch.Size([3, 4, 5]), torch.Size([5, 4, 3]))

In [74]:
some_t.stride(), transpose_t.stride()

((20, 5, 1), (1, 5, 20))

In [75]:
#contigous tensor:
points.is_contiguous(), points_t.is_contiguous()

(True, False)

In [76]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [77]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [78]:
points_t.stride()

(1, 2)

In [79]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [80]:
points_t_cont.stride()

(3, 1)

In [81]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [82]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')
points_gpu

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='cuda:0')

In [83]:
points_gpu = points.to(device='cuda')
points_gpu

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='cuda:0')

In [85]:
points_gpu = points.to(device='cuda:0')
points_gpu

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='cuda:0')

In [86]:
points = 2 * points #CPU
points_gpu = 2 * points.to(device='cuda') #GPU

In [87]:
points_gpu = points_gpu + 4 #still gpu

In [88]:
points_cpu = points_gpu.to(device='cpu')

In [89]:
points_gpu = points.cuda()
points_gpu = points.cuda(0)
points_cpu = points_gpu.cpu()

In [90]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [91]:
points = torch.from_numpy(points_np)

In [93]:
torch.save(points, '../data/ourpoints.t') 

In [94]:
with open('../data/ourpoints.t','wb') as f:
    torch.save(points, f)

In [95]:
points = torch.load('../data/ourpoints.t')

In [96]:
with open('../data/ourpoints.t','rb') as f:
    points = torch.load(f)

In [97]:
import h5py
f = h5py.File('../data/ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

In [98]:
f = h5py.File('../data/ourpoints.hdf5', 'r')
dset = f['coords']
last_points = dset[-2:]
last_points

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [99]:
last_points = torch.from_numpy(dset[-2:])
f.close()
last_points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## Exercises

In [100]:
# Create a tensor a from list(range(9)). Predict and then check the size, offset, and stride.
tens = torch.tensor(range(9))
tens

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [102]:
tens.stride(), tens.shape, tens.size(), tens.storage_offset()

((1,), torch.Size([9]), torch.Size([9]), 0)

In [103]:
#Create a new tensor using b = a.view(3, 3). What does view do? Check that a and b share the same storage.
tens_b = tens.view(3, 3)
tens_b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [105]:
id(tens_b.storage()) == id(tens.storage())

True

In [106]:
tens_c = tens_b[1:,1:]
tens_c.stride(), tens_c.shape, tens_c.size(), tens_c.storage_offset()

((3, 1), torch.Size([2, 2]), torch.Size([2, 2]), 4)

In [108]:
torch.math.cos(tens_b)

ValueError: only one element tensors can be converted to Python scalars

In [110]:
torch.cos(tens_b)

tensor([[ 1.0000,  0.5403, -0.4161],
        [-0.9900, -0.6536,  0.2837],
        [ 0.9602,  0.7539, -0.1455]])

In [111]:
tens_b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [122]:
tens_b = tens_b.to(torch.long)

In [119]:
tens_b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])